/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veriyapilarodev2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aizen
 */
public class LinkedlistTest extends javax.swing.JFrame {

    linkedlist linkedlist = new linkedlist();
    BST bst[] = null;
    String line;

    /**
     * Creates new form LinkedlistTest
     */
    public LinkedlistTest() {
        initComponents();
        this.path.setEnabled(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        OKunanDosyaYolu = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        islemcalistir = new javax.swing.JButton();
        Aramayap = new javax.swing.JRadioButton();
        Listele = new javax.swing.JRadioButton();
        Cikis = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        AranacakKelime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        show = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Dosya Yolu oku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        OKunanDosyaYolu.setText("Okunan Dosya Yolu");

        jLabel2.setText("islem Secenekleri :");

        islemcalistir.setText("islem calistir");
        islemcalistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islemcalistirActionPerformed(evt);
            }
        });

        buttonGroup1.add(Aramayap);
        Aramayap.setText("Arama Yap");

        buttonGroup1.add(Listele);
        Listele.setText("Listele");

        buttonGroup1.add(Cikis);
        Cikis.setText("Cikis");

        jLabel3.setText("Aranacak Kelime");

        show.setColumns(20);
        show.setRows(5);
        jScrollPane1.setViewportView(show);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Listele)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Aramayap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(47, 47, 47)
                                        .addComponent(islemcalistir)))
                                .addGap(42, 42, 42)
                                .addComponent(AranacakKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cikis)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OKunanDosyaYolu)
                            .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OKunanDosyaYolu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(islemcalistir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aramayap)
                    .addComponent(jLabel3)
                    .addComponent(AranacakKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Listele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cikis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File dosya[];
        String Aderss = "C:\\Users\\Aizen\\Documents\\NetBeansProjects\\DataStr_Homework_01_AhmetTekalan\\VeriYapilarOdev2";
        path.setText(Aderss);
        dosya = finder(path.getText());
        for (int i = dosya.length - 1; i >= 0; i--) {
            linkedlist.addFirst(dosya[i]);
        }
        bst = new BST[linkedlist.size()];
        NodeLL temp = linkedlist.head;
        try {
            for (int i = 0; i < bst.length; i++) {
                bst[i] = new BST();
            }
            for (int i = 0; i < bst.length; i++) {
                bst[i].addthewordtoBST(temp.value.toString());
                temp = temp.next;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LinkedlistTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void islemcalistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islemcalistirActionPerformed
        try {
            if (Aramayap.isSelected()) {
                String gelenKelime[];
                boolean kelimekonturlu = true;
                if (AranacakKelime.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Lutfen aranacak kelime secin  ");
                } else {
                    NodeLL temp = linkedlist.head;
                    for (int i = 0; i < bst.length; i++) {
                        bst[i].inorder();
                        gelenKelime = bst[i].Nodeler.split(" ");
                        for (int j = 0; j < gelenKelime.length; j++) {
                            if (gelenKelime[j].equals(AranacakKelime.getText())) {
                                show.setText(null);
                                show.append("Aranan Kelime  : " + gelenKelime[j]);
                                show.append("\n");
                                File f = new File(temp.value.toString());
                                show.append("dosya adi : " + f.getName());
                                kelimekonturlu = false;
                            }
                        }
                        temp = temp.next;
                    }
                    if (kelimekonturlu) {
                        show.setText(null);
                        JOptionPane.showMessageDialog(this, "boyle bir kelime bulunmadi! ");
                    }
                }
            }
            if (Listele.isSelected()) {
                show.setText(null);
                NodeLL temp = linkedlist.head;
                for (int i = 0; i < bst.length; i++) {
                    bst[i].inorder();
                    File f = new File(temp.value.toString());
                    show.append(f.getName());
                    show.append("\n ");
                    show.append(bst[i].Nodeler);
                    show.append("\n ");
                    temp = temp.next;
                }
            }
            if (Cikis.isSelected()) {
                this.setVisible(false);
            }
        } catch (java.lang.NullPointerException rx) {
            JOptionPane.showMessageDialog(this, "Lutfen dosya konumu sectiniz ");
        }
    }//GEN-LAST:event_islemcalistirActionPerformed
    public static File[] finder(String dirName) {
        File dir = new File(dirName);
        return dir.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String filename) {
                return filename.endsWith(".txt");
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkedlistTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkedlistTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkedlistTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkedlistTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkedlistTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aramayap;
    private javax.swing.JTextField AranacakKelime;
    private javax.swing.JRadioButton Cikis;
    private javax.swing.JRadioButton Listele;
    private javax.swing.JLabel OKunanDosyaYolu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton islemcalistir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField path;
    private javax.swing.JTextArea show;
    // End of variables declaration//GEN-END:variables
}
