/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author EXT02D6270
 */
public class main extends javax.swing.JFrame {

    DefaultListModel<String> listModel;
    DefaultTreeModel mode;
    HashTable<Integer, String> table;

    public main() {
        initComponents();
        this.setLocationRelativeTo(this);
        listModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnDosyaOku = new javax.swing.JButton();
        btnYazdir = new javax.swing.JButton();
        rbInOrder = new javax.swing.JRadioButton();
        rbPostOrder = new javax.swing.JRadioButton();
        rbLevelOrder = new javax.swing.JRadioButton();
        rbPreOrder = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTraverse = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        display = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDosyaOku.setText("file read");
        btnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaOkuActionPerformed(evt);
            }
        });

        btnYazdir.setText("write");
        btnYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYazdirActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbInOrder);
        rbInOrder.setText("In Order");

        buttonGroup1.add(rbPostOrder);
        rbPostOrder.setText("Post Order");

        buttonGroup1.add(rbLevelOrder);
        rbLevelOrder.setText("Level Order");

        buttonGroup1.add(rbPreOrder);
        rbPreOrder.setText("Pre Order");

        txtAreaTraverse.setColumns(20);
        txtAreaTraverse.setRows(5);
        jScrollPane2.setViewportView(txtAreaTraverse);

        jLabel1.setText("Hash Table");

        jLabel2.setText("Traverse Sonucu");

        jScrollPane3.setViewportView(jList1);

        display.setText("display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnYazdir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDosyaOku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbInOrder)
                                    .addComponent(rbPreOrder)
                                    .addComponent(rbLevelOrder)
                                    .addComponent(rbPostOrder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(171, 171, 171)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDosyaOku)
                        .addGap(18, 18, 18)
                        .addComponent(rbInOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPostOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbLevelOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPreOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(display)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYazdir)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYazdirActionPerformed
        if (rbInOrder.isSelected()) {
            txtAreaTraverse.setText(null);
            for (int i = 0; i < table.tree.size(); i++) {
                table.tree.get(i).inorder(table.tree.get(i).root);
                txtAreaTraverse.append(" \n ");
            }
        } else if (rbPreOrder.isSelected()) {
            txtAreaTraverse.setText(null);
            for (int i = 0; i < table.tree.size(); i++) {
                table.tree.get(i).preorder(table.tree.get(i).root);
                txtAreaTraverse.append(" \n ");

            }
        } else if (rbPostOrder.isSelected()) {
            txtAreaTraverse.setText(null);
            for (int i = 0; i < table.tree.size(); i++) {
                table.tree.get(i).postorder(table.tree.get(i).root);
                txtAreaTraverse.append(" \n ");

            }
        } else if (rbLevelOrder.isSelected()) {
            txtAreaTraverse.setText(null);
            for (int i = 0; i < table.tree.size(); i++) {
                table.tree.get(i).levelOrderTraversal();
                txtAreaTraverse.append(" \n ");

            }
        }

    }//GEN-LAST:event_btnYazdirActionPerformed

    private void btnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaOkuActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String fileName = f.getAbsolutePath();
            int val = 0;
            BufferedReader br = null;

            br = new BufferedReader(new FileReader(fileName));
            val = Integer.parseInt(br.readLine()); // txt den ilk satırı alır
            table = new HashTable(val);

            String word = null;
            while ((word = br.readLine()) != null) {
                table.put((word.length() + val), word);
            }

            for (int i = 0; i < table.tree.size(); i++) {
                listModel.addElement((String) table.tree.get(i).root.data);
            }

            jList1.setModel(listModel);
        } catch (IOException | NumberFormatException | NullPointerException e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_btnDosyaOkuActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        DynamicTreeDemo demo = new DynamicTreeDemo(this);
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                demo.createAndShowGUI();
            }
        });
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosyaOku;
    private javax.swing.JButton btnYazdir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbInOrder;
    private javax.swing.JRadioButton rbLevelOrder;
    private javax.swing.JRadioButton rbPostOrder;
    private javax.swing.JRadioButton rbPreOrder;
    public static javax.swing.JTextArea txtAreaTraverse;
    // End of variables declaration//GEN-END:variables
}
